export interface PlannedStop {
  address: string;
  area: string;
  category: "coffee" | "food" | "temple";
  duration: string;
  hours: string;
  id: string;
  image: string;
  name: string;
  rating: string;
  reviews: string;
  secondImage: string;
  time: string;
  travelAfter?: {
    detail: string;
    mode: "walk";
  };
  type: string;
}

export const FRIDAY_STOPS: readonly PlannedStop[] = [
  {
    address: "1-294 Kiyomizu, Higashiyama",
    area: "Higashiyama",
    category: "temple",
    duration: "1.5 hours",
    hours: "06:00–18:00",
    id: "kiyomizu",
    image: "/images/temple.png",
    name: "Kiyomizu-dera",
    rating: "4.6",
    reviews: "5,240",
    secondImage: "/images/kyoto.png",
    time: "09:00",
    travelAfter: { detail: "18 min · 1.2 km", mode: "walk" },
    type: "Temple",
  },
  {
    address: "87-5 Hoshinocho, Higashiyama",
    area: "Higashiyama",
    category: "coffee",
    duration: "45 min",
    hours: "09:00–18:00",
    id: "arabica",
    image: "/images/coffee.png",
    name: "% Arabica Higashiyama",
    rating: "4.4",
    reviews: "2,186",
    secondImage: "/images/kyoto.png",
    time: "11:00",
    travelAfter: { detail: "12 min · 800 m", mode: "walk" },
    type: "Coffee",
  },
  {
    address: "Nishikikoji-dori, Nakagyo",
    area: "Nakagyo",
    category: "food",
    duration: "1 hour",
    hours: "10:00–18:00",
    id: "nishiki",
    image: "/images/market.png",
    name: "Nishiki Market",
    rating: "4.3",
    reviews: "8,420",
    secondImage: "/images/kyoto.png",
    time: "12:30",
    type: "Lunch",
  },
  {
    address: "68 Fukakusa Yabunouchicho, Fushimi",
    area: "Fushimi",
    category: "temple",
    duration: "1 hour",
    hours: "08:30–17:00",
    id: "fushimi-inari-senbon-torii",
    image: "/images/temple.png",
    name: "Fushimi Inari Taisha Senbon Torii Observation Path",
    rating: "4.7",
    reviews: "12,480",
    secondImage: "/images/kyoto.png",
    time: "14:00",
    travelAfter: { detail: "22 min · 1.6 km", mode: "walk" },
    type: "Shrine",
  },
  {
    address: "Arashiyama, Ukyo",
    area: "Arashiyama",
    category: "temple",
    duration: "1 hour",
    hours: "08:30–16:30",
    id: "arashiyama-bamboo-grove-north-entrance",
    image: "/images/temple.png",
    name: "Arashiyama Bamboo Grove North Entrance Walking Route",
    rating: "4.5",
    reviews: "9,310",
    secondImage: "/images/kyoto.png",
    time: "15:00",
    travelAfter: { detail: "18 min · 1.3 km", mode: "walk" },
    type: "Garden",
  },
  {
    address: "1 Kinkakujicho, Kita",
    area: "Kita",
    category: "temple",
    duration: "45 min",
    hours: "09:00–17:00",
    id: "kinkakuji-golden-pavilion-garden",
    image: "/images/temple.png",
    name: "Kinkaku-ji Golden Pavilion Garden Viewing Terrace",
    rating: "4.6",
    reviews: "10,204",
    secondImage: "/images/kyoto.png",
    time: "16:00",
    travelAfter: { detail: "14 min · 900 m", mode: "walk" },
    type: "Temple",
  },
  {
    address: "Jodoji Ishibashicho, Sakyo",
    area: "Sakyo",
    category: "temple",
    duration: "1 hour",
    hours: "All day",
    id: "philosophers-path-canal-promenade",
    image: "/images/temple.png",
    name: "Philosopher's Path Canal-side Cherry Tree Promenade",
    rating: "4.4",
    reviews: "6,780",
    secondImage: "/images/kyoto.png",
    time: "17:00",
    travelAfter: { detail: "16 min · 1.1 km", mode: "walk" },
    type: "Walk",
  },
  {
    address: "Higashiyama Sanjo, Higashiyama",
    area: "Higashiyama",
    category: "temple",
    duration: "45 min",
    hours: "All day",
    id: "keage-incline-historic-railway",
    image: "/images/temple.png",
    name: "Keage Incline Historic Railway and Slope Viewpoint",
    rating: "4.3",
    reviews: "3,921",
    secondImage: "/images/kyoto.png",
    time: "18:00",
    travelAfter: { detail: "11 min · 750 m", mode: "walk" },
    type: "Landmark",
  },
  {
    address: "625 Gionmachi Kitagawa, Higashiyama",
    area: "Gion",
    category: "temple",
    duration: "45 min",
    hours: "06:00–18:00",
    id: "yasaka-shrine-lantern-courtyard",
    image: "/images/temple.png",
    name: "Yasaka Shrine Main Gate and Evening Lantern Courtyard",
    rating: "4.5",
    reviews: "7,114",
    secondImage: "/images/kyoto.png",
    time: "19:00",
    travelAfter: { detail: "8 min · 600 m", mode: "walk" },
    type: "Shrine",
  },
  {
    address: "Shirakawa, Gion",
    area: "Gion",
    category: "food",
    duration: "1 hour",
    hours: "17:00–22:00",
    id: "gion-shirakawa-machiya-riverside",
    image: "/images/market.png",
    name: "Gion Shirakawa Traditional Machiya Riverside District",
    rating: "4.2",
    reviews: "2,648",
    secondImage: "/images/kyoto.png",
    time: "20:00",
    travelAfter: { detail: "12 min · 850 m", mode: "walk" },
    type: "District",
  },
  {
    address: "Nanzenji Fukuchicho, Sakyo",
    area: "Sakyo",
    category: "temple",
    duration: "1 hour",
    hours: "08:40–17:00",
    id: "nanzenji-sanmon-hojo-garden",
    image: "/images/temple.png",
    name: "Nanzen-ji Temple Sanmon Gate and Hojo Garden",
    rating: "4.6",
    reviews: "5,982",
    secondImage: "/images/kyoto.png",
    time: "21:00",
    travelAfter: { detail: "15 min · 1 km", mode: "walk" },
    type: "Temple",
  },
  {
    address: "3 Kyoto-Gyoen, Kamigyo",
    area: "Kamigyo",
    category: "temple",
    duration: "1 hour",
    hours: "09:00–16:30",
    id: "kyoto-imperial-palace-sento-garden",
    image: "/images/temple.png",
    name: "Kyoto Imperial Palace Sento Garden Southern Entrance",
    rating: "4.4",
    reviews: "4,105",
    secondImage: "/images/kyoto.png",
    time: "22:00",
    travelAfter: { detail: "20 min · 1.4 km", mode: "walk" },
    type: "Garden",
  },
  {
    address: "15 Honmachi, Higashiyama",
    area: "Higashiyama",
    category: "temple",
    duration: "1 hour",
    hours: "08:30–16:30",
    id: "tofukuji-tsutenkyo-maple-corridor",
    image: "/images/temple.png",
    name: "Tofuku-ji Tsutenkyo Bridge Maple Viewing Corridor",
    rating: "4.5",
    reviews: "8,067",
    secondImage: "/images/kyoto.png",
    time: "23:00",
    type: "Temple",
  },
];
